### ISSUE TITLE
The style of the buttons when hovered.

### ISSUE THREAD

**Issue by RaminMammadzada** [Berabjesus/New-York-Times-article-page#2]
The style of the icons is not like in the original when they have hovered. 

The line in the codebase: https://github.com/Berabjesus/New-York-Times-article-page/blob/38350972100564df8a385f59d51df12098431319/index.html#L62

Your version when hovered:
![image](https://user-images.githubusercontent.com/4702114/84786846-f033db00-aff5-11ea-8d52-e6cceab785e4.png)

In the original version when hovered:
![image](https://user-images.githubusercontent.com/4702114/84787183-591b5300-aff6-11ea-9029-7d898d312499.png)

At the same time, the background colours of the icons are not the same.

**Comment by Berabjesus** [comment]
Thank you! Fixed.
